# Generated by Django 3.2.5 on 2023-03-08 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
    ]
